pom.xml
src/main/java/org/jenkinsci/plugins/pluginusage/analyzer/BuilderJobAnalyzer.java
src/main/java/org/jenkinsci/plugins/pluginusage/analyzer/MavenJobAnalyzer.java
src/main/java/org/jenkinsci/plugins/pluginusage/analyzer/StepAnalyser.java

https://wiki.jenkins.io/display/JENKINS/Tips+for+optional+dependencies

Handle plugins as optional dependencies correctly

---

src/main/java/org/jenkinsci/plugins/pluginusage/PluginUsageView.java
src/test/java/org/jenkinsci/plugins/pluginusage/PluginUsageIT.java
src/test/java/org/jenkinsci/plugins/pluginusage/api/Plugin.java
src/test/java/org/jenkinsci/plugins/pluginusage/api/PluginProjects.java
src/test/java/org/jenkinsci/plugins/pluginusage/api/PluginUsage.java
src/test/java/org/jenkinsci/plugins/pluginusage/api/Project.java

Action methods getDisplayName, getIconFileName, getUrlName should
return null if this action is to be hidden from users.
https://www.jenkins.io/doc/developer/extensibility/action-for-all-projects/

Fix permissions for UnprotectedRootAction

---

pom.xml
src/test/java/org/jenkinsci/plugins/pluginusage/JenkinsClient.java
src/test/java/org/jenkinsci/plugins/pluginusage/PluginUsageIT.java

 Upgrade Plugin Parent to 4.40

---

src/main/java/org/jenkinsci/plugins/pluginusage/JobsPerPlugin.java
src/main/java/org/jenkinsci/plugins/pluginusage/analyzer/AbstractProjectAnalyzer.java
src/main/java/org/jenkinsci/plugins/pluginusage/analyzer/ComputedFolderAnalyzer.java
src/main/java/org/jenkinsci/plugins/pluginusage/analyzer/JobCollector.java
src/main/java/org/jenkinsci/plugins/pluginusage/analyzer/MatrixProjectAnalyzer.java
src/main/java/org/jenkinsci/plugins/pluginusage/analyzer/MavenProjectAnalyzer.java
src/main/java/org/jenkinsci/plugins/pluginusage/analyzer/PipelineProjectAnalyzer.java
src/main/java/org/jenkinsci/plugins/pluginusage/analyzer/ProjectAnalyzer.java
src/test/java/org/jenkinsci/plugins/pluginusage/PluginUsageIT.java
src/test/resources/multibranch_pipeline1.xml
src/test/resources/multibranch_pipeline2.xml

Adds Computed Folders Analyzer

---

src/main/java/org/jenkinsci/plugins/pluginusage/JobsPerPlugin.java
src/test/java/org/jenkinsci/plugins/pluginusage/JenkinsClient.java

Use diamond operator and removed unnecessary semicolon and import

Refactoring: Use diamond operator and removed unnecessary semicolon and import

---

Jenkinsfile
pom.xml
src/test/java/org/jenkinsci/plugins/pluginusage/PluginUsageIT.java

https://www.jenkins.io/blog/2022/12/14/require-java-11/

Require Jenkins 2.361.4 and Java 11

---

src/main/java/org/jenkinsci/plugins/pluginusage/JobsPerPlugin.java

This changes the meaning of the Has Dependants? column to exclude optional dependencies.

Replaces hasDependants with hasMandatoryDependents

---

src/main/java/org/jenkinsci/plugins/pluginusage/analyzer/PipelineLastBuildAnalyzer.java

Uses a HashSet to not process the same run multiple times in pipeline jobs

---

src/main/resources/org/jenkinsci/plugins/pluginusage/PluginUsageView/index.jelly

Update pipeline warning for both scripted and pipeline

---

src/main/java/org/jenkinsci/plugins/pluginusage/JobsPerPlugin.java
src/main/java/org/jenkinsci/plugins/pluginusage/PersistedModel.java
src/main/java/org/jenkinsci/plugins/pluginusage/PluginUsageAsyncPeriodicWork.java
src/main/java/org/jenkinsci/plugins/pluginusage/PluginUsageModel.java
src/main/java/org/jenkinsci/plugins/pluginusage/PluginUsageView.java
src/main/java/org/jenkinsci/plugins/pluginusage/analyzer/JobCollector.java
src/main/resources/org/jenkinsci/plugins/pluginusage/PluginUsageView/index.jelly
src/main/resources/org/jenkinsci/plugins/pluginusage/PluginUsageView/index.properties
src/test/java/org/jenkinsci/plugins/pluginusage/JenkinsClient.java
src/test/java/org/jenkinsci/plugins/pluginusage/PluginUsageIT.java
src/test/java/org/jenkinsci/plugins/pluginusage/PluginUsageViewApiTest.java
src/test/resources/org/jenkinsci/plugins/pluginusage/PluginUsageViewApiTest/shouldRenderJson/plugin-usage.xml

JENKINS-71329 Plugin Usage page not loading
```[tasklist]
```

Adds AsyncPeriodicWork with persistence to make loading faster

---

src/main/java/org/jenkinsci/plugins/pluginusage/PersistedModel.java
src/test/resources/multibranch_pipeline2.xml

getItem does not get by full display name
```[tasklist]
```

Fix persisted model to use full name instead of display name

---

src/main/java/org/jenkinsci/plugins/pluginusage/PersistedModel.java

The plugin would fail to render properly if a user
- has PluginView permission
- has Job Discover permission
- does not have Job Read permission
https://issues.jenkins.io/browse/JENKINS-73288 Plugin Usage is null even with PluginView permission

Fix NullPointerException for user with discover permission

---

pom.xml

Upgrade parent pom from 4.83 to 4.87

---

pom.xml

Use maven-plugin from jenkins bom

---

pom.xml

Update testcontainers to 1.20.1

---

pom.xml
src/main/java/org/jenkinsci/plugins/pluginusage/PluginUsageModel.java
src/test/java/org/jenkinsci/plugins/pluginusage/PluginUsageViewApiTest.java
src/test/java/org/jenkinsci/plugins/pluginusage/api/PluginUsage.java

Hi, i'd like too add OthersPlugin to be accessible from API call.
Running mvn test ends with 13 pass tests. api.json shows how the api works after the change

Add api support to othersPlugin field in PluginUsageView  

---

pom.xml
src/test/java/org/jenkinsci/plugins/pluginusage/PluginUsageIT.java

Removes unused token-macro dependency

---

pom.xml
src/main/java/org/jenkinsci/plugins/pluginusage/analyzer/JobCollector.java
src/main/java/org/jenkinsci/plugins/pluginusage/analyzer/SCMSourceAnalyzer.java
src/test/java/org/jenkinsci/plugins/pluginusage/PluginUsageIT.java
src/test/resources/scmSource1.xml

Adds support for SCMSource

---

src/main/resources/org/jenkinsci/plugins/pluginusage/PluginUsageView/index.jelly
src/main/resources/org/jenkinsci/plugins/pluginusage/PluginUsageView/show-hide.js

JENKINS-74075 [plugin-usage-plugin] Extract inline script block and event handler in org/jenkinsci/plugins/pluginusage/PluginUsageView/index.jelly

Extract inline script block and event handler

---

pom.xml

Upgrade parent pom from 4.87 to 4.88

---

pom.xml

Upgrade testcontainers

---

pom.xml

Not necessary since "Modernize to Jenkins 2.375.4" ([d749c6a0ace5773c2b8378241a45b4a6ac8c4bfc](https://github.com/jenkinsci/plugin-usage-plugin/pull/47)) in version 4.2.

Removes managed version for commons-net

---

pom.xml

Gets conditional-buildstep version from bom-2.479.x Gets maven-failsafe-plugin version from parent POM

Removes specific versions from POM

---

src/main/java/org/jenkinsci/plugins/pluginusage/PluginUsageView.java

https://issues.jenkins.io/browse/JENKINS-73255

Migrate from EE 8 to EE 9

---

.mvn/extensions.xml
.mvn/maven.config
pom.xml

Cleans up the plugin build and enables incremental builds for easy testing of PRs following the latest archetype.
`mvn clean verify`

Clean up plugin build
